GET http://localhost:5070

###Get all games
GET http://localhost:5070/games

###Get games by id
GET http://localhost:5070/games/2

###Create a game
POST http://localhost:5070/games
Content-Type: application/json

{
  "name": "Game 2",
  "genre": "Action",
  "price": 100,
  "releaseDate": "2021-01-01"
}

###Update a game
PUT http://localhost:5070/games/2
Content-Type: application/json

{
  "name": "Game 23",
  "genre": "Action",
  "price": 100,
  "releaseDate": "2021-01-01"
}

###Delete a game
DELETE  http://localhost:5070/games/2